config/routes.rb
Rails.application.routes.draw do
  resources :test_resources

  root 'clients#index'

  resources :clients

end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/models/test_resource.rb
class TestResource < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :find_client, only: [:show, :edit, :update, :destroy]

  def index
    @clients = Client.all
  end

  def edit
  end

  def update
    if @client.update(client_params)
      redirect_to @client, notice: "Client was created."
    else
      render action: 'edit'
    end
  end

  private
    def find_client
      @client = Client.find(params[:id])
    end

    def client_params
      params.require(:client).permit(:name, :description, :vision)
    end
end

app/controllers/test_resources_controller.rb
class TestResourcesController < ApplicationController
  before_action :set_test_resource, only: [:show, :edit, :update, :destroy]

  # GET /test_resources
  def index
    @test_resources = TestResource.all
  end

  # GET /test_resources/1
  def show
  end

  # GET /test_resources/new
  def new
    @test_resource = TestResource.new
  end

  # GET /test_resources/1/edit
  def edit
  end

  # POST /test_resources
  def create
    @test_resource = TestResource.new(test_resource_params)

    if @test_resource.save
      redirect_to @test_resource, notice: 'Test resource was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /test_resources/1
  def update
    if @test_resource.update(test_resource_params)
      redirect_to @test_resource, notice: 'Test resource was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /test_resources/1
  def destroy
    @test_resource.destroy
    redirect_to test_resources_url, notice: 'Test resource was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_resource
      @test_resource = TestResource.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def test_resource_params
      params.require(:test_resource).permit(:attr1, :attr2, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/clients/_client.html.erb
<div class="client">
  <h1><%= link_to client.name, edit_client_path(client) %></h1>
  <h2><%= client.description %></h2>
  <p><%= client.vision %></p>
</div>
<hr/>

app/views/clients/edit.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

  <div>
    <%= f.label :vision %><br>
    <%= f.text_field :vision %>
  </div>

  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/clients/index.html.erb
<%= render @clients %>

app/views/clients/show.html.erb
<div>
  <h1><%= @client.name %></h1>
  <h2><%= @client.description %></h2>
  <p><%= @client.vision %></p>
  <%= link_to "Clients", clients_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Showcase</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/test_resources/_form.html.erb
<%= form_for(@test_resource) do |f| %>
  <% if @test_resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_resource.errors.count, "error") %> prohibited this test_resource from being saved:</h2>

      <ul>
      <% @test_resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :attr1 %><br>
    <%= f.text_field :attr1 %>
  </div>
  <div class="field">
    <%= f.label :attr2 %><br>
    <%= f.text_field :attr2 %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/test_resources/edit.html.erb
<h1>Editing test_resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @test_resource %> |
<%= link_to 'Back', test_resources_path %>

app/views/test_resources/index.html.erb
<h1>Listing test_resources</h1>

<table>
  <thead>
    <tr>
      <th>Attr1</th>
      <th>Attr2</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @test_resources.each do |test_resource| %>
      <tr>
        <td><%= test_resource.attr1 %></td>
        <td><%= test_resource.attr2 %></td>
        <td><%= test_resource.description %></td>
        <td><%= link_to 'Show', test_resource %></td>
        <td><%= link_to 'Edit', edit_test_resource_path(test_resource) %></td>
        <td><%= link_to 'Destroy', test_resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Test resource', new_test_resource_path %>

app/views/test_resources/new.html.erb
<h1>New test_resource</h1>

<%= render 'form' %>

<%= link_to 'Back', test_resources_path %>

app/views/test_resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Attr1:</strong>
  <%= @test_resource.attr1 %>
</p>

<p>
  <strong>Attr2:</strong>
  <%= @test_resource.attr2 %>
</p>

<p>
  <strong>Description:</strong>
  <%= @test_resource.description %>
</p>

<%= link_to 'Edit', edit_test_resource_path(@test_resource) %> |
<%= link_to 'Back', test_resources_path %>